export default class API { };

/**
 * 用户接口地址
 */
API.ROOT_URL = ROOT_URL


API.APPID = '';
API.APPNAME = '';
API.CONTEXT_PATH = '/web';


API.PASSPORT_API = API.CONTEXT_PATH + '/passport';
API.ADMIN_API = API.CONTEXT_PATH + '/admin';
API.DEVICE_API = API.CONTEXT_PATH + '/device';
API.APPLICATION_API = API.CONTEXT_PATH + '/apps';


// DEVICE API
API.APP_LIST = API.DEVICE_API + '/apps';

API.DEVICE_LIST = API.DEVICE_API + '/list';
API.DEVICE_EXPORT = API.DEVICE_API + '/sn/export';

API.DEVICE_DETAIL = API.DEVICE_API + '/detail';

API.DEVICE_DELETE = API.DEVICE_API + '/delete';

API.DEVICE_ENABLE = API.DEVICE_API + '/enable';

API.SN_MAKE_CONFIG = API.DEVICE_API + '/sn/config';

API.SN_SAVE_CONFIG = API.DEVICE_API + '/sn/saveconfig';

API.SN_MAKE = API.DEVICE_API + '/sn/create';

API.SN_MAKE_LIST = API.DEVICE_API + '/sn/createlist';

API.SN_CHECK = API.DEVICE_API + '/sn/checkbatch';

API.SN_DOWN_URL = API.DEVICE_API + '/sn/downloadurl';

API.SN_SS_ADD = API.DEVICE_API + '/statistics/ssadd';

API.SN_CHECK_LIST = API.DEVICE_API + '/sn/checklist';

API.SN_MANUAL_MAKE = API.DEVICE_API + '/sn/manualmake';

API.SN_CAN_MANUAL = API.DEVICE_API + '/sn/canmanual';

API.SN_RANGE = API.DEVICE_API + '/sn/range';

API.DEVICE_SNTASK_LIST = API.DEVICE_API + '/sn-task/list';
API.DEVICE_SNTASK_ACK = API.DEVICE_API + '/sn-task/ack';
API.DEVICE_SNTASK_NEW = API.DEVICE_API + '/sn-task/new';

// permission
API.PERMISSION_ACCOUNT_CREATE = API.ADMIN_API + '/user/add'
API.PERMISSION_ACCOUNT_RESET_PASSWD = API.ADMIN_API + '/user/reset-passport'
API.PERMISSION_ACCOUNT_LIST = API.ADMIN_API + '/user/list'
API.PERMISSION_SYSTEM_LIST = API.ADMIN_API + '/system/list'
API.PERMISSION_SYSTEM_EDIT = API.ADMIN_API + '/system/edit'
API.PERMISSION_SYSTEM_ADD = API.ADMIN_API + '/system/add'
API.PERMISSION_SYSTEM_SHOW = API.ADMIN_API + '/system/show'

API.PERMISSION_ROLE_LIST = API.ADMIN_API + '/role/list'
API.PERMISSION_ROLE_EDIT = API.ADMIN_API + '/role/edit'
API.PERMISSION_ROLE_SHOW = API.ADMIN_API + '/role/show'
API.PERMISSION_ROLE_ADD = API.ADMIN_API + '/role/add'
API.PERMISSION_ROLE_DEL = API.ADMIN_API + '/role/del'

API.PERMISSION_PERM_LIST = API.ADMIN_API + '/permission/list'
API.PERMISSION_PERM_ADD = API.ADMIN_API + '/permission/add'
API.PERMISSION_PERM_EDIT = API.ADMIN_API + '/permission/edit'
API.PERMISSION_PERM_SHOW = API.ADMIN_API + '/permission/show'
API.PERMISSION_PERM_DEL = API.ADMIN_API + '/permission/del'

API.PERMISSION_USERROLE_ADD = API.ADMIN_API + '/userrole/add'
API.PERMISSION_USERROLE_EDIT = API.ADMIN_API + '/userrole/edit'
API.PERMISSION_USERROLE_INFO = API.ADMIN_API + '/userrole/info'
API.PERMISSION_USERROLE_SHOW = API.ADMIN_API + '/userrole/show'
API.PERMISSION_USERROLE_DEL = API.ADMIN_API + '/userrole/del'

API.PERMISSION_MENU_ADD = API.ADMIN_API + '/menu/add'
API.PERMISSION_MENU_EDIT = API.ADMIN_API + '/menu/edit'
API.PERMISSION_MENU_SHOW = API.ADMIN_API + '/menu/show'
API.PERMISSION_MENU_LIST = API.ADMIN_API + '/menu/list'
API.PERMISSION_MENU_DEL = API.ADMIN_API + '/menu/del'

API.PERMISSION_ROLEMENU_LIST = API.ADMIN_API + '/rolemenu/list'
API.PERMISSION_ROLEMENU_ADD = API.ADMIN_API + '/rolemenu/add'

//// Application API
API.APPICATION_CREATE_APP = API.APPLICATION_API + '/create'
API.APPICATION_APPLIST = API.APPLICATION_API + '/list'

//// OTA
API.OTA_GET_VERSION = '/not_exists'

//// PASSPORT
API.USER_LOGOUT = '/web/logout';
API.CURRENT_USER_INFO = API.PASSPORT_API + '/session'
API.CURRENT_USER_EDIT = '/web/user/edit'

API.ROLE_MEUN = API.PASSPORT_API + '/menus';

