name: BUILD-DOCKER
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}