name: BUILD-DOCKER
on:
  pull_request:
    branches: [ dev/v*, init ]

jobs:
  build-and-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV; echo $APP_VERSION
      
      - name: Update Code
        run: rm -rf .git* .env.example && mv build/production.env .env && rm -rf build/build.sh

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aproton/iotservice
          tags: v0.1-$APP_VERSION, latest
          registry: registry.cn-beijing.aliyuncs.com
          dockerfile: build/Dockerfile
          username: ${{ secrets.ALIYUN_DOCKER_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
  test-deploy:
    needs: build-and-docker
    runs-on: self-hosted
    steps:
      - name: Deploy Test Env
#        if: startsWith()
        run: echo "deploy test env"