name: BUILD-DOCKER
on:
  pull_request:
    branches: [ main ]

jobs:
  init-env:
    runs-on: ubuntu-latest
    steps:
      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_PASSWORD }}

  build-service:
    needs: init-env
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV; cat $GITHUB_ENV | grep APP_VERSION
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: aproton/iotservice
        tags: v0.1-$APP_VERSION
        registry: docker.io
        directory: .
        dockerfile: ./build/deploy/Dockerfile
        username: ${{ secrets.DOCKERHUB_DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKERHUB_DOCKER_PASSWORD }}

  test-deploy:
    needs: build-service
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Test Env
        run: echo "deploy test env"

