name: BUILD-DOCKER
on:
  pull_request:
    branches: [ main ]

jobs:
  init-env:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_PASSWORD }}
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV; echo $APP_VERSION

  build-service:
    needs: init-env
    runs-on: self-hosted
    container:
      image: docker.io/aproton/iotservice-dev:latest
    steps:  
      - name: Update Code
        run: bash build/build_to_deploy.sh

  docker:
    needs: build-service
    runs-on: self-hosted
    steps:  
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: aproton/iotservice
        tags: v0.1-$APP_VERSION, latest
        registry: docker.io
        directory: build/deploy
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKERHUB_DOCKER_PASSWORD }}

  test-deploy:
    needs: build-service
    runs-on: self-hosted
    steps:
      - name: Deploy Test Env
#        if: startsWith()
        run: echo "deploy test env"

  build-cleanup:
    if: always()
    needs: [build-service, docker, test-deploy]
    runs-on: self-hosted
    container:
      image: docker.io/aproton/iotservice-dev:latest
    steps:  
      - name: Cleanup Content
        run: bash build/build_cleanup.sh