name: BUILD-DOCKER
on:
  pull_request:
    branches: [ dev/v*, init ]
  push:
    branches: [ init ]

jobs:
  build-and-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV; echo $GITHUB_ENV
      
      - name: Update Code
        run: rm -rf .git* .env.example && mv build/production.env .env && rm -rf build/build.sh

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aproton/iotservice
          tags: v0.1-test, latest
          registry: registry.cn-beijing.aliyuncs.com
          dockerfile: build/Dockerfile
          username: ${{ secrets.ALIYUN_DOCKER_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}